apiVersion: v1
kind: Namespace
labels:
  istio-injection: enabled
metadata:
  name: httpserver
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpserver
  namespace: httpserver
data:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  namespace: httpserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpserver
      role: backend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        app: httpserver
        role: backend
    spec:
      affinity: # 反亲和设置，让pod尽量分布在不同节点
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                    - httpserver
              topologyKey: kubernetes.io/hostname
      containers:
      - name: httpserver
        image: vincent616/httpserver:v1.0.3@sha256:fe1c2edbfeb61044d6fd768225e40d1f328b1cb2f9be63f6e1acb62328e2a855
        imagePullPolicy: IfNotPresent
        env:
          - name: VERSION
            value: "1.0.3"
          - name: GLOG_LEVEL
            value: "1"
        ports:
          - name: httpserver-port
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: httpserver-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          terminationGracePeriodSeconds: 60
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: httpserver-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: # qosClass: Guaranteed
          requests:
            cpu: 100m
            memory: 90Mi
          limits:
            cpu: 100m
            memory: 90Mi
      nodeSelector:
        kubernetes.io/os: linux
